/*
 * Neon CRM API Reference
 *
 * Welcome to the Neon CRM API v2. This version is a complete rebuild of the existing [API v1](https://developer.neoncrm.com/api) and adopts many modern RESTful API conventions. API v2 also introduces new methods for working with custom fields and events, in addition to updating and extending the functionality of all the existing methods from v1.  API v2 has two possible base URLs, depending on the type of Neon CRM instance you are using: - **Production & Sandbox Instances:** [https://api.neoncrm.com/v2](https://api.neoncrm.com/v2) - **Trial Instances:** [https://trial.neoncrm.com/v2](https://trial.neoncrm.com/v2)  ### Authorization API v2 authorizes all requests using [HTTP basic authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). Use the values below for the username and password pair in the `Authorization` header of your request. - *Username* – The organization ID of your Neon CRM instance - *Password* – An API key associated with a user in the instance  Learn [how to obtain an org ID and API key](https://developer.neoncrm.com/authentication/) from your Neon CRM instance.  ### Versioning This API is versioned to allow for ongoing fixes and updates to the API that may include backwards-incompatible changes. Specify the API version by including the header `NEON-API-VERSION: 2.X` with every request. The current version is listed at the top of these docs.  Learn more about [versioning in API v2](https://developer.neoncrm.com/versioning/).  ### Legacy Events vs New Events Currently, only [legacy events](https://support.neonone.com/hc/en-us/articles/18441378851981-Legacy-Events-Vs-Events) are supported within Neon CRM's API. [Follow this page for updates.](https://developer.neoncrm.com/updates/)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package neon

import (
	"encoding/json"
	"strings"
	"time"
)

type Event struct {
	Id                          string             `json:"id,omitempty"`
	Name                        string             `json:"name,omitempty"`
	Summary                     string             `json:"summary,omitempty"`
	Code                        string             `json:"code,omitempty"`
	MaximumAttendees            int32              `json:"maximumAttendees,omitempty"`
	Category                    *IdNamePair        `json:"category,omitempty"`
	Topic                       *IdNamePair        `json:"topic,omitempty"`
	Campaign                    *IdNamePair        `json:"campaign,omitempty"`
	PublishEvent                bool               `json:"publishEvent,omitempty"`
	EnableEventRegistrationForm bool               `json:"enableEventRegistrationForm,omitempty"`
	Archived                    bool               `json:"archived,omitempty"`
	EnableWaitListing           bool               `json:"enableWaitListing,omitempty"`
	CreateAccountsforAttendees  bool               `json:"createAccountsforAttendees,omitempty"`
	EventDescription            string             `json:"eventDescription,omitempty"`
	EventDates                  *EventDates        `json:"eventDates,omitempty"`
	FinancialSettings           *FinancialSettings `json:"financialSettings,omitempty"`
	Location                    *Location          `json:"location,omitempty"`
}

type EventDates struct {
	StartDate             CustomDateJson `json:"startDate,omitempty"`
	EndDate               CustomDateJson `json:"endDate,omitempty"`
	StartTime             string         `json:"startTime,omitempty"`
	EndTime               string         `json:"endTime,omitempty"`
	RegistrationOpenDate  CustomDateJson `json:"registrationOpenDate,omitempty"`
	RegistrationCloseDate CustomDateJson `json:"registrationCloseDate,omitempty"`
	TimeZone              *IdNamePair    `json:"timeZone,omitempty"`
}

type Location struct {
	Name           string        `json:"name,omitempty"`
	RoomNumber     string        `json:"roomNumber,omitempty"`
	BuildingNumber string        `json:"buildingNumber,omitempty"`
	Address        string        `json:"address,omitempty"`
	City           string        `json:"city,omitempty"`
	StateProvince  *CodeNamePair `json:"stateProvince,omitempty"`
	Country        *IdNamePair   `json:"country,omitempty"`
	ZipCode        string        `json:"zipCode,omitempty"`
	ZipCodeSuffix  string        `json:"zipCodeSuffix,omitempty"`
}

type FinancialSettings struct {
	FeeType                string                      `json:"feeType,omitempty"`
	AdmissionFee           *AdmissionFee               `json:"admissionFee,omitempty"`
	TicketsPerRegistration *TicketsPerRegistration     `json:"ticketsPerRegistration,omitempty"`
	Fund                   *IdNamePair                 `json:"fund,omitempty"`
	TaxDeductiblePortion   *TaxDeductiblePortion       `json:"taxDeductiblePortion,omitempty"`
	Donations              *FinancialSettingsDonations `json:"donations,omitempty"`
}

type CustomDateJson struct {
	time.Time
}

func (c *CustomDateJson) UnmarshalJSON(b []byte) (err error) {
	s := strings.Trim(string(b), "\"")

	if s == "null" {
		c.Time = time.Time{}
		return
	}

	c.Time, err = time.Parse("2006-01-02", s)
	return
}

func (c CustomDateJson) MarshalJSON() ([]byte, error) {
	return json.Marshal(time.Time(c.Time))
}
